In [17]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split  
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics 

In [4]:
df = pd.read_csv('../datasets/Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
feature_names = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
X = df[feature_names]
y = df['Species']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

## Feature Scaling

It is good to scale your data in order to allow all of it to be uniformly evaluated. This can be done with either normalization or standardization. Here I will be using normalization to scale the data to be between a value of 0 - 1.

In [11]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Training & Predictions

K-Neighbours is implemented using sklearn.neighbours. It will be intialized using 5 as the K-Value in order to test it. The potential of adding in a function that runs through a number of different K-values is a viable option to add to the program.

In [19]:
classifier = KNeighborsClassifier(n_neighbors=3)  
classifier.fit(X_train, y_train) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [20]:
y_pred = classifier.predict(X_test)  

In [21]:
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))  

[[10  0  0]
 [ 0 12  1]
 [ 0  0  7]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.92      0.96        13
 Iris-virginica       0.88      1.00      0.93         7

    avg / total       0.97      0.97      0.97        30



In [23]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9666666666666667
